from .linear_regression import LinearRegression as LinearRegression
from .quadratic_regression import QuadraticRegression as QuadraticRegression
from .logistic_regression import LogisticRegression as LogisticRegression